# yaml 配置实例
version: '3.7'
services:
  peppaf:
    image: vuenginxcontainer
    ports:
      - 3000:80
    depends_on:
      - peppab
  peppab:
    image: peppa-backend-peppab
    ports:
      - "5000:5000"
    depends_on:
      - mysqldb
  mysqldb:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - D:/Docker/mysqlData:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: Peppa
