"""empty message

Revision ID: 1aa19ff1bfd0
Revises: baf89ba069e1
Create Date: 2023-04-24 13:09:55.237947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1aa19ff1bfd0'
down_revision = 'baf89ba069e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_project', schema=None) as batch_op:
        batch_op.drop_constraint('user_project_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'project', ['project_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_project', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_project_ibfk_1', 'project', ['project_id'], ['id'])

    # ### end Alembic commands ###
